version: '3.9'
services:
  client:
   container_name: vc-frontend
   init: true
   build:
    context: ./client
   restart: always
   ports: 
    - 3000:3000
   env_file:
    - ./client/.env.docker
    - ./client/.env
  
  authservice:
   container_name: vc-authservice
   init: true
   build:
    context: ./authservice
   restart: always
   ports:
    - 6969:6969
   environment:
     - NODE_ENV: "PRODUCTION"
     - PORT: 6969
     - SECRET_KEY: /run/secrets/secret_key
     - SENDER_GMAIL_ADDRESS: /run/secrets/sender_gmail_address
     - SENDER_GMAIL_ACCESS_TOKEN: /run/secrets/gmail_access_token
     - SENDER_GMAIL_CLIENT_ID: /run/secrets/gmail_client_id
     - SENDER_GMAIL_CLIENT_SECRET: /run/secrets/gmail_client_secret
     - SENDER_GMAIL_REFRESH_TOKEN: /run/secrets/gmail_refresh_token
     - DB_HOST: /run/secrets/db_host
     - DB_PORT: 5432
     - DB_USERNAME: /run/secrets/db_username
     - DB_PASSWORD: /run/secrets/db_password
     - ACCESS_TOKEN_SECRET: /run/secrets/access_token_secret
     - REFRESH_TOKEN_SECRET: /run/secrets/refresh_token_secret
   secrets:
     - secret_key
     - sender_gmail_address
     - gmail_access_token
     - gmail_client_id
     - gmail_client_secret
     - gmail_refresh_token
     - db_host
     - db_username
     - db_password
     - access_token_secret
     - refresh_token_secret

secrets:
  secret_key:
   file: /private/secretKey.txt
  sender_gmail_address:
   file: /private/senderGmailAddr.txt
  gmail_access_token:
   file: /private/gmailAccessToken.txt
  gmail_client_id:
   file: /private/gmailClientId.txt
  gmail_client_secret:
   file: /private/gmailCLientSecret.txt
  gmail_refresh_token:
   file: /private/gmailRefreshToken.txt
  db_host:
   file: /private/dbHost.txt
  db_username: 
   file: /private/dbUsername.txt
  db_password:
   file: /private/dbPassword.txt
  access_token_secret:
   file: /private/accessTokenSecret.txt
  refresh_token_secret:
   file: /private/refreshTokenSecret.txt
  
