version: '3.9'
services:
  client:
   container_name: vc-frontend
   init: true
   build:
    context: ./client
   restart: always
   ports: 
    - 3000:3000
   env_file:
    - ./client/.env.sample
  
  authservice:
   container_name: vc-backend
   init: true
   build:
    context: ./backend
   restart: always
   ports:
    - 6969:6969
   env_file:
    - ./backend/.env.sample
