name: PULL REQUEST ON MASTER

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Running Tests on Client service
        run: cd client && npm install && npm run test
      - name: Running Tests on Auth service
        run: cd authservice && npm install && npm run test
      - name: Build Docker
        run: docker-compose build
      # preview deplyment thing