name: PUSH ON MASTER BRANCH

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Installing dependencies
        run: npm install
      - name: Build Docker
        run: docker-compose build
      - name: Run Tests
        run: npm run test
        # production deployment thing